### ISSUE TITLE
Add compiled binaries for version_102

### ISSUE THREAD

**Issue by junderw** [WebAssembly/binaryen#4341] opened 2021-11-17 06:13 UTC
The release page has binaries for up to 101, but 102 only has the source tarballs.

If you could upload them I'd appreciate it.

Thanks.

**Comment by kripken** [comment] 2021-11-17 21:27
cc @sbc100 - I think you know the build system here best?

**Comment by sbc100** [comment] 2021-11-17 22:56
This a duplicate of #3651 I think.   Our github action that is supposed to add this binaries is no longer working sadly..

**Comment by sbc100** [comment] 2021-11-17 22:57
Sorry duplicate of #4148

**Closed** 2021-11-17 22:57 UTC
