### ISSUE TITLE
Minor tee_local optimization

### ISSUE THREAD

**Issue by dcodeIO** [WebAssembly/binaryen#1331] opened 2017-12-08 15:43 UTC
This might - or might not - be an optimization opportunity for the optimizer:

Source ([context](https://github.com/AssemblyScript/next/blob/master/tests/compiler/memcpy.ts#L7-L10)):

```ts
  while (n && s % 4) {
    store<u8>(d++, load<u8>(s++));
    n--;
  }
```

Is then compiled to the following unoptimized condition by me ([context](https://github.com/AssemblyScript/next/blob/master/tests/compiler/memcpy.wast#L109-L118)). (Note that there is a significant chance that what I'm doing with temp locals there to emulate a JS-like result of the condition is stupid. Anyway, the issue is merely about the optimization performed below.).

```s
     (if (result i32)
      (tee_local $7
       (get_local $2)
      )
      (i32.rem_s
       (get_local $4)
       (i32.const 4)
      )
      (get_local $7)
     )
```

This is then optimized by Binaryen to ([context](https://github.com/AssemblyScript/next/blob/master/tests/compiler/memcpy.optimized.wast#L18-L27)), using default optimization passes:

```s
    (if (result i32)
     (tee_local $3
      (get_local $2)
     )
     (i32.rem_s
      (get_local $1)
      (i32.const 4)
     )
     (get_local $3)
    )
```

Seems to me the `tee_local $3` could be avoided altogether by just using `get_local $2` instead, because `$3` isn't read afterwards, but always set again (for example [here](https://github.com/AssemblyScript/next/blob/master/tests/compiler/memcpy.optimized.wast#L31) or [here](https://github.com/AssemblyScript/next/blob/master/tests/compiler/memcpy.optimized.wast#L302)). Not sure if an optimization here could also lead to one less local ultimately.

Are you interested in issues like this one? Just let me know if you are not, not a problem. As always, I might also be overlooking something here.

**Comment by kripken** [comment] 2017-12-08 17:52
> Are you interested in issues like this one? 

Definitely, yes :) Thanks for filing!

So looking at
````
(module
 (memory $0 0)
 (export "test" (func $test))
 (func $test (param $7 i32) (param $2 i32) (param $4 i32) (result i32)
  (if (result i32)
   (tee_local $7
    (get_local $2)
   )
   (i32.rem_s
    (get_local $4)
    (i32.const 4)
   )
   (get_local $7)
  )
 )
)
````
The issue is that the `tee_local` is "in the way" of optimizing it, and `-O` has no effect. But we can solve that with `--flatten --ssa`, those flatten out things like `tee_local` (into sets on a block), and ensure each use has a different name. That's then much more similar to what LLVM would emit. And running `--flatten --ssa -O`, we get
````
  (if
   (get_local $1)
   (set_local $1
    (i32.rem_s
     (get_local $2)
     (i32.const 4)
    )
   )
  )
  (get_local $1)
````
which has indeed managed to remove the `tee`.

We don't run `--flatten` or `--ssa` by default, because they enlarge the IR quite a lot, and it's not necessary on what LLVM gives us anyhow. But perhaps we should, at least in `-O3` or `-Oz`? Anyhow, it might make sense for your compiler to run those passes before the main optimizations.

**Comment by dcodeIO** [comment] 2017-12-08 18:11
I see, thanks a lot. Just tried it with first running flatten/ssa ([like so](https://github.com/AssemblyScript/next/blob/0ebb99a33c9c47c202d40660082ac3138b192a09/src/module.ts#L703-L711)), but that [doesn't seem to produce the same result](https://github.com/AssemblyScript/next/blob/0ebb99a33c9c47c202d40660082ac3138b192a09/tests/compiler/memcpy.optimized.wast) for me.

I'd assume that order is important there somehow?

**Comment by kripken** [comment] 2017-12-08 19:29
Hmm, that looks wrong, yeah. The order does matter, you must run `--flatten --ssa` before the normal optimizations. Does your `runPasses` queue them for later, perhaps? Or maybe somethings going wrong with running them just on the current function, and they apply to the module? Can check in the shell that `wasm-opt --flatten --ssa -O` does what is expected (if not, that could be a serious bug).

**Comment by dcodeIO** [comment] 2017-12-08 19:38
My implementation is supposed to call the respective C-API functions directly, no queueing. This is the API trace of just the call to `optimize()`:

```
// beginning a Binaryen API trace
#include <math.h>
#include <map>
#include "src/binaryen-c.h"
int main() {
  std::map<size_t, BinaryenFunctionTypeRef> functionTypes;
  std::map<size_t, BinaryenExpressionRef> expressions;
  std::map<size_t, BinaryenFunctionRef> functions;
  std::map<size_t, RelooperBlockRef> relooperBlocks;
  BinaryenModuleRef the_module = NULL;
  RelooperRef the_relooper = NULL;
  {
    const char* passes[] = { "flatten", "ssa" };
    BinaryenModuleRunPasses(the_module, passes, 2);
  }
  BinaryenModuleOptimize(the_module);
  return 0;
}
```

**Comment by kripken** [comment] 2017-12-08 20:23
That looks correct, so this might be a bug. Do you also see this problem in the shell using `wasm-opt`? Can you provide the wast file?

**Comment by dcodeIO** [comment] 2017-12-08 20:39
Sure! This is the wast being optimized:
[memcpy.wast](https://github.com/AssemblyScript/next/blob/64516eecfb068c91681ad4fe71ed5310b9c4f579/tests/compiler/memcpy.wast)

This is the wast generated from the above using `wasm-opt --flatten --ssa -O`:
[memcpy.wasm-opt-flatten-ssa-O.wast](https://github.com/AssemblyScript/next/blob/64516eecfb068c91681ad4fe71ed5310b9c4f579/tests/compiler/memcpy.wasm-opt-flatten-ssa-O.wast)

The latter seems to be identical to what the compiler generated through `optimize()`.

**Comment by kripken** [comment] 2017-12-08 23:28
Thanks, now I see. While in the tiny testcase those passes work, in the full file, `ssa` has some issues that make it cause those nested tees. That'll need to be optimized (`ssa` is still experimental), I think it's causing too many long overlapping lifetimes, and we don't currently break those up.

But looking at this more closely, perhaps we should optimize it better directly. It looks like `coalesce-locals` does a poor job on
````
     (if (result i32)
      (tee_local $7
       (get_local $2)
      )
      (i32.rem_s
       (get_local $4)
       (i32.const 4)
      )
      (get_local $7)
     )
     [ $7 is never used again, $2 is ]
````
It thinks `$7` and `$2` can't be merged because their lifetimes overlap, which is technically true, but not actually a problem since on the overlap their values are identical. This definitely seems like something we should optimize. It doesn't seem super-easy, though, we'd need to track values in that pass, and not just lifetimes. An alternative might be to add a pass for this specific thing, which would run before coalesce-locals.

**Closed** 2018-01-08 02:35 UTC
