### ISSUE TITLE
asm2wasm fails with: bad processUnshifted ["binary", ">>", "$12", 2]

### ISSUE THREAD

**Issue by jakogut** [WebAssembly/binaryen#1718] opened 2018-11-01 18:16 UTC
I'm compiling an application that uses libvlc, and during wasm generation, asm2wasm fails with the message `bad processUnshifted ["binary", ">>", "$12", 2]`, and returns -6.

The command I'm using for compilation is below.

`EMCC_DEBUG=2 emcc -O0 -v -s ASSERTIONS=1 -s SAFE_HEAP=1 -s USE_PTHREADS=1 -Iinclude -Llib/.libs -Lsrc/.libs/ -lvlccore -lvlc main.c -o main.js`

The output of the command with debugging enabled can be viewed here.

https://gist.github.com/jakogut/e54ea4fd0f9599f8db3b93d0c383bc07

Attached is the generated asm.js file that triggers the problem.

[main.temp.asm.zip](https://github.com/WebAssembly/binaryen/files/2539551/main.temp.asm.zip)

I've tried binaryen 50 and 51 with the same results.

EDIT: Here's the output with `--debug`:

https://gist.github.com/jakogut/affb97baf9d2969ed04d44ef435241dd

**Comment by kripken** [comment] 2018-11-01 21:30
Thanks for the bug report! The problem is in `_module_EndBank`, where there is
```
     $14 = (Atomics_compareExchange(HEAP8, $12>>2,$13,0)|0);
```
I opened https://github.com/WebAssembly/binaryen/pull/1720 which fixes this, however, it's possible that the backend is not emitting the right code there - can you provide the source code to that function, to verify?

**Comment by jakogut** [comment] 2018-11-01 21:50
Thanks for such awesome projects!

Here's the source for that function: https://github.com/videolan/vlc/blob/3.0.0-git/src/modules/bank.c#L610

I'll test out that fix, and get back to you in a minute.

**Comment by jakogut** [comment] 2018-11-01 22:06
It builds! Ship it!

You're a fucking wizard.

**Comment by kripken** [comment] 2018-11-01 22:34
Great, thanks for confirming!

Looking at that source, I am guessing `vlc_mutex_lock` expands into an atomic operation. Hard to tell in the source though - can you provide the bitcode maybe?

**Comment by jakogut** [comment] 2018-11-01 23:44
Here you go.

[libvlc_bitcode.zip](https://github.com/WebAssembly/binaryen/files/2540493/libvlc_bitcode.zip)

**Comment by kripken** [comment] 2018-11-02 00:40
Thanks @jakogut!

Ok, the bad news is that I think the backend is doing something wrong here, so that PR does get things compiling but the result may be incorrect if it runs that code. I'll investigate more.

**Comment by jakogut** [comment] 2018-11-02 16:28
I'm unsure if that's a problem for my application yet. I'll likely need plugins for things like codecs and muxers, but those will likely be linked in to the application, and won't necessarily need to be loaded dynamically like VLC traditionally does.

**Comment by kripken** [comment] 2018-11-02 22:43
Fixed by that PR landing.

About dynamic linking, that does work but is not much optimized in the current state. We hope to optimize and complete it reasonably soon.

**Closed by kripken** 2018-11-02 22:43 UTC
