### ISSUE TITLE
crash in wasm-opt at -O2

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/binaryen#3697] opened 2021-03-17 18:09 UTC
The wasm2.test_poppler test is failing consistenly with recent builds of wasm-opt:

https://app.circleci.com/pipelines/github/emscripten-core/emscripten/11775/workflows/4dd05dca-592a-47f3-9e74-671debdfd795/jobs/404629

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
em++: error: '/root/emsdk/upstream/bin/wasm-opt --post-emscripten --no-exit-runtime -O2 --low-memory-unused --zero-filled-memory --strip-producers pdfimages.wasm -o pdfimages.wasm -g --mvp-features' failed (-6)
make[2]: *** [pdfimages] Error 1
make[2]: *** Waiting for unfinished jobs....
```

I have not yet bisected to a particular binaryen commit but I suspect its something in the last 24 hours.

**Comment by kripken** [comment] 2021-03-17 18:36
I don't see this locally. Perhaps it is running out of memory. I don't think we've changed anything on the Binaryen side that could explain it. Perhaps an LLVM change is causing more code or locals to be emitted?

**Comment by sbc100** [comment] 2021-03-17 18:52
I can't repro it locally either.  Strange.  I wonder if its circleci change?

**Comment by sbc100** [comment] 2021-03-17 18:54
Actually I can repro locally if I do `./emsdk install tot` and use that.

**Comment by sbc100** [comment] 2021-03-17 19:05
Seems to be related to the binaryen binaryen built on the waterfall.

**Comment by kripken** [comment] 2021-03-17 19:50
Interesting, if you can reproduce this with the waterfall builds then we can bisect it at least.

Looks like the sheriff is @aheejin - do you have time? Or did you intend to @sbc100 ? If neither then I can find time.

**Comment by kripken** [comment] 2021-03-17 23:13
@aheejin Actually I just tried this again before I saw you self-assigned this and I can get this to reproduce locally. From the stack trace it is in debug info code, so likely my fault or wouter - I can verify shortly.

**Comment by kripken** [comment] 2021-03-18 02:23
This was actually LLVM's "fault" for emitting different DWARF now. So this was a crash in all opt levels actually, whenever we rewrote DWARF. Fix in https://github.com/WebAssembly/binaryen/pull/3700

**Closed** 2021-03-18 18:41 UTC

**Comment by sbc100** [comment] 2021-03-18 19:06
Do you want to make a PR to re-enable the poppler test? (or I can if you like)

**Comment by kripken** [comment] 2021-03-18 19:28
I will. Still waiting on the binaryen roll.
