### ISSUE TITLE
Wasm2JS: Add support for i64.trunc_sat_f64_s & sibling etc.

### ISSUE THREAD

**Issue by tjelsm** [WebAssembly/binaryen#5366] opened 2022-12-20 13:59 UTC
I've been attempting to use Wasm2JS but I've been proven unsuccessful. The response on my WASM file when running is `Fatal: error in validating wasm2js output`. However, all of the other tools in the toolchain works on the file, as well as running the WASM, so it is a valid binary. 

I'm not sure if this is just part of how WASM2JS prints the WAT file when an error occurs but it prints:
```
 )
 ;; custom section "producers", size 129
 ;; features section: mutable-globals, nontrapping-float-to-int, bulk-memory, sign-ext
)
```
Towards the end, I'm unsure if this signifies anything. 

If it's relevant, this is a TinyGo -> WASM binary.

**Comment by kripken** [comment] 2022-12-20 17:01
Can you provide the wasm it fails on? Hopefully it's a simple bug to fix.

(those custom and feature section comments are normal when printing a module)

**Comment by tjelsm** [comment] 2023-01-18 21:24
I've linked it below zipped, as it didn't allow WASM as a file type, I've not managed to get it working yet but hopefully some insight can be provided on this. 😄 

[test.zip](https://github.com/WebAssembly/binaryen/files/10451203/test.zip)

**Comment by kripken** [comment] 2023-01-18 23:25
Thanks, and this does look like a bug. Reduced testcase:
```wat
(module
 (memory $0 2)

 (table $0 1 1 funcref)
 (elem (i32.const 1) $0)

 (func $0
  (drop
   (select
    (i64.trunc_sat_f64_s
     (f64.const 0)
    )
    (i64.const 0)
    (i32.const 0)
   )
  )
  (i64.store
   (i32.const 0)
   (i64.const 1)
  )
  (unreachable)
 )
)
```

```
$ bin/wasm-opt -all --flatten --i64-to-i32-lowering
[wasm-validator error in function 0] local.set's value type must be correct, on 
(local.set $0
 (i64.trunc_sat_f64_s
  (f64.const 0)
 )
)
Fatal: error after opts
```

**Comment by kripken** [comment] 2023-01-18 23:33
The problem is that the `src/passes/I64ToI32Lowering.cpp` pass lacks support for some of the truncating/saturating operations, like `i64.trunc_sat_f64_s`.

To fix it, the pass needs to get support for `TruncSatSFloat64ToInt32`. For comparison, it already has support for `TruncUFloat64ToInt64` (`i64.trunc_f64_u`).

I'm not sure offhand how much work that is. Renaming this issue to track that.

**Comment by tjelsm** [comment] 2023-01-18 23:57
Is there any quick fix I can do on my part to work around this?

also, is this not referring to the same issue you opened in 2019? https://github.com/WebAssembly/binaryen/issues/2198

**Comment by tjelsm** [comment] 2023-01-19 00:09
On further inspection, this type is actually built into the TinyGo syscall/js, so this affects all binaries.

**Comment by kripken** [comment] 2023-01-19 00:49
Good find, let's close this then as a duplicate of that one.

**Closed by kripken** 2023-01-19 00:49 UTC
