### ISSUE TITLE
Hang on validation

### ISSUE THREAD

**Issue by DuncanUszkay1** [WebAssembly/binaryen#2845] opened 2020-05-10 21:52 UTC
Hello, I was making some changes to [Assemblyscript](https://github.com/AssemblyScript/assemblyscript) which seem to be causing the binaryen.js validation command to hang indefinitely:
```typescript
console.log("start validate")
var result = binaryen._BinaryenModuleValidate(this.ref) == 1
console.log("done validating")
```
```bash
$ asc main.ts --runtime half --validate -b output.wasm -t output.wat
start validate
// hangs indefinitely
```

I'm still able to compile and run the module, which seems to work fine. 

Since it's this feature is new I'm not surprised that there is a validation error, but I am surprised that validation fails to run at all.

There's also an assertion failure when skipping validation and optimizing, but I suppose the true issue here is that validation is hanging.

Any insight/advice on moving forward here would be greatly appreciated. I'll likely be gathering more information on this in the meantime.

Some files that would possibly be of interest:
- module.emitText(false) output, minimal code segment: https://gist.github.com/DuncanUszkay1/745e672013fe20630d4ee2e62692e0fe
- full module.emitText(false) output post compilation: https://gist.github.com/DuncanUszkay1/98cb9d30fc2f3cdae8ef807482dd6c32
- full module.emitStackIR(true) output post compilation: https://gist.github.com/DuncanUszkay1/7ba9c3835b878180cc1674ec37f7b851
- optimization error output: https://gist.github.com/DuncanUszkay1/5c9877a92ad61dec840d23aa92031d40

**Comment by kripken** [comment] 2020-05-11 16:27
To check if this is a binaryen.js issue or a general binaryen issue, you can try to validate it in `wasm-opt` on the commandline. If that hangs then please provide the wasm file.

**Comment by DuncanUszkay1** [comment] 2020-05-11 17:18
It appears that running wasm-opt on the emitted wat works just fine, no optimization or validation errors at all. I guess that shows that it's a binaryen.js problem 🤔

**Comment by MaxGraey** [comment] 2020-05-11 17:29
I should notice that AS has own pass pipeline which currently differs with binaryen `-O4`:
https://github.com/AssemblyScript/assemblyscript/blob/master/src/module.ts#L1473

So it may be a key. But before this custom pipeline don't cause to problems

**Comment by DuncanUszkay1** [comment] 2020-05-11 17:31
Does the pass pipeline effect validation? Since that's the real problem here

**Comment by DuncanUszkay1** [comment] 2020-05-11 17:32
It doesn't seem like that should matter if validation occurs before any passes are run though 🤔

**Comment by MaxGraey** [comment] 2020-05-11 17:33
Validation pass as last step (after optimizations) so yes

**Comment by DuncanUszkay1** [comment] 2020-05-11 18:46
I've resolved the underlying problem, which turned out to be an invalid type. So I guess the repro here is to just put in a huge number instead of a normal `NativeType` into a local_get (`5534224` in my case, a pointer to an expression) and try to validate using binaryen.js

**Comment by tlively** [comment] 2020-05-12 06:38
Unfotunately there's no sanity checking we can do in general to check that a `Type` is valid without large performance regressions. User code just has to be careful not to accidentally use invalid types. I'll close the issue because this bug has been resolved.

**Closed by tlively** 2020-05-12 06:38 UTC
