### ISSUE TITLE
Binaryen doesn't preserve memory size when writing .wasm file.

### ISSUE THREAD

**Issue by eholk** [WebAssembly/binaryen#870] opened 2017-01-04 23:52 UTC
This came up in trying to update mir2wasm. I ran mir2wasm on a trivial test file, and get the following .wast:

```
eholk@eholk-macbookair:~/wasm/mir2wasm [binaryen-update] $ cargo run -- tests/compile-pass/trivial.rs -o trivial.wasm
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/mir2wasm tests/compile-pass/trivial.rs -o trivial.wasm`
(module
  (type $rustfn-0-3 (func))
  (type $__wasm_start (func))
  (memory $0 1024 1024)
  (export "memory" (memory $0))
  (export "main" (func $main))
  (export "rust_entry" (func $__wasm_start))
  (func $main (type $rustfn-0-3)
    (local $0 i32)
    (local $1 i32)
    (local $2 i64)
    (block $block$1$break
      (set_local $0
        (i32.load
          (i32.const 0)
        )
      )
      (block
        (br $block$1$break)
      )
    )
    (block
      (block $block$2$break
        (block $bb0
        )
        (block
          (br $block$2$break)
        )
      )
      (block
        (block $bb1
          (i32.store
            (i32.const 0)
            (get_local $0)
          )
          (return)
        )
      )
    )
  )
  (func $__wasm_start (type $__wasm_start)
    (i32.store
      (i32.const 0)
      (i32.const 65535)
    )
    (call $main)
  )
)
```

This version appears to have a memory size of 1024 pages. Unfortunately, V8 fails to instantiate this module. Looking at wasm-dis gives a possible hint as to why:

```
eholk@eholk-macbookair:~/wasm/mir2wasm [binaryen-update] $ ./wasm-install/bin/wasm-dis ./trivial.wasm 
(module
  (type $0 (func))
  (type $1 (func))
  (memory $0 0)
  (export "memory" (memory $0))
  (export "main" (func $main))
  (export "rust_entry" (func $__wasm_start))
  (func $main (type $0)
    (local $var$0 i32)
    (local $var$1 i32)
    (local $var$2 i64)
    (block $label$0
      (block $label$1
        (set_local $var$0
          (i32.load
            (i32.const 0)
          )
        )
        (block $label$2
          (br $label$1)
        )
      )
      (block $label$3
        (block $label$4
          (block $label$5
          )
          (block $label$6
            (br $label$4)
          )
        )
        (block $label$7
          (block $label$8
            (i32.store
              (i32.const 0)
              (get_local $var$0)
            )
            (return)
          )
        )
      )
    )
  )
  (func $__wasm_start (type $1)
    (block $label$0
      (i32.store
        (i32.const 0)
        (i32.const 65535)
      )
      (call $main)
    )
  )
)
```

Here the memory has size 0.

Using wasm2wast gives an error:

```
eholk@eholk-macbookair:~/wasm/mir2wasm [binaryen-update] $ ./wasm-install/bin/wasm2wast ./trivial.wasm 
error: @0x0000002e: invalid export memory index
```

Talking with @dschuff, it seems like mir2wasm or binaryen may be generating an invalid module, leading to an invalid .wasm, which then behaves differently depending on the tool.

Here is a trace of the API calls mir2wasm made:

```
// beginning a Binaryen API trace
#include <math.h>
#include <map>
#include "src/binaryen-c.h"
int main() {
  std::map<size_t, BinaryenFunctionTypeRef> functionTypes;
  std::map<size_t, BinaryenExpressionRef> expressions;
  std::map<size_t, BinaryenFunctionRef> functions;
  std::map<size_t, RelooperBlockRef> relooperBlocks;
  BinaryenModuleRef the_module = NULL;
  RelooperRef the_relooper = NULL;
  the_module = BinaryenModuleCreate();
  expressions[size_t(NULL)] = BinaryenExpressionRef(NULL);
  BinaryenModuleAutoDrop(the_module);
  {
    const char* segments[] = { 0 };
    BinaryenExpressionRef segmentOffsets[] = { 0 };
    BinaryenIndex segmentSizes[] = { 0 };
    BinaryenSetMemory(the_module, 256, 256, "memory", segments, segmentOffsets, segmentSizes, 0);
  }
  the_relooper = RelooperCreate();
  {
    BinaryenExpressionRef children[] = { 0 };
    expressions[1] = BinaryenBlock(the_module, "bb0", children, 0);
  }
  relooperBlocks[0] = RelooperAddBlock(the_relooper, expressions[1]);
  expressions[2] = BinaryenGetLocal(the_module, 0, 1);
  expressions[3] = BinaryenConst(the_module, BinaryenLiteralInt32(0));
  expressions[4] = BinaryenStore(the_module, 4, 0, 0, expressions[3], expressions[2], 1);
  expressions[5] = BinaryenReturn(the_module, expressions[0]);
  {
    BinaryenExpressionRef children[] = { expressions[4], expressions[5] };
    expressions[6] = BinaryenBlock(the_module, "bb1", children, 2);
  }
  relooperBlocks[1] = RelooperAddBlock(the_relooper, expressions[6]);
  RelooperAddBranch(relooperBlocks[0], relooperBlocks[1], expressions[0], expressions[0]);
  {
    BinaryenIndex paramTypes[] = { 0 };
    functionTypes[0] = BinaryenAddFunctionType(the_module, "rustfn-0-3", 0, paramTypes, 0);
  }
  expressions[7] = BinaryenConst(the_module, BinaryenLiteralInt32(0));
  expressions[8] = BinaryenLoad(the_module, 4, 0, 0, 0, 1, expressions[7]);
  expressions[9] = BinaryenSetLocal(the_module, 0, expressions[8]);
  relooperBlocks[2] = RelooperAddBlock(the_relooper, expressions[9]);
  RelooperAddBranch(relooperBlocks[2], relooperBlocks[0], expressions[0], expressions[0]);
  expressions[10] = RelooperRenderAndDispose(the_relooper, relooperBlocks[2], 1, the_module);
  {
    BinaryenType varTypes[] = { 1, 1, 2 };
    functions[0] = BinaryenAddFunction(the_module, "main", functionTypes[0], varTypes, 3, expressions[10]);
  }
  BinaryenAddExport(the_module, "main", "main");
  {
    BinaryenIndex paramTypes[] = { 0 };
    functionTypes[1] = BinaryenAddFunctionType(the_module, "__wasm_start", 0, paramTypes, 0);
  }
  {
    const char* segments[] = { 0 };
    BinaryenExpressionRef segmentOffsets[] = { 0 };
    BinaryenIndex segmentSizes[] = { 0 };
    BinaryenSetMemory(the_module, 1024, 1024, NULL, segments, segmentOffsets, segmentSizes, 0);
  }
  expressions[11] = BinaryenConst(the_module, BinaryenLiteralInt32(65535));
  expressions[12] = BinaryenConst(the_module, BinaryenLiteralInt32(0));
  expressions[13] = BinaryenStore(the_module, 4, 0, 0, expressions[12], expressions[11], 1);
  {
    BinaryenExpressionRef operands[] = { 0 };
    expressions[14] = BinaryenCall(the_module, "main", operands, 0, 0);
  }
  {
    BinaryenExpressionRef children[] = { expressions[13], expressions[14] };
    expressions[15] = BinaryenBlock(the_module, NULL, children, 2);
  }
  BinaryenAddExport(the_module, "__wasm_start", "rust_entry");
  {
    BinaryenType varTypes[] = { 0 };
    functions[1] = BinaryenAddFunction(the_module, "__wasm_start", functionTypes[1], varTypes, 0, expressions[15]);
  }
  BinaryenModuleValidate(the_module);
  return 0;
}
```

**Comment by kripken** [comment] 2017-01-05 00:29
Thanks, the problem was just the memory wasn't marked as existing. Fix in #871.

Nice how the tracing stuff helps here, as the problem wasn't reproducible without it, this was a pure C API bug.

**Comment by eholk** [comment] 2017-01-05 00:31
As I was looking into this I thought "Wouldn't it be nice if there were a way to trace all the API calls and arguments so people could reproduce this without having to run mir2wasm." Lo and behold, there was! I'm seriously impressed.

**Comment by qwertie** [comment] 2017-01-05 08:53
Where is this trace thingie and how does it work?

**Comment by kripken** [comment] 2017-01-05 18:34
See the [C API header](https://github.com/WebAssembly/binaryen/blob/master/src/binaryen-c.h#L426), it describes how it works too. It's also tested in `test/example/c-api-kitchen-sink.c` so you can see it and its output there: `c-api-kitchen-sink.c` is the source, `c-api-kitchen-sink.txt` the output of running it, which contains the executable trace, and `c-api-kitchen-sink.txt.txt` contains the output of running that trace, so we test that the trace works too.

**Closed** 2017-01-05 18:59 UTC
