### ISSUE TITLE
check.py should not download and run precompiled binaries

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/binaryen#264] opened 2016-03-20 21:51 UTC
I claim that it should be possible, and in fact the default behavior, for binaryen's tests to run without downloading precompiled native binaries for any purpose. Among other issues:
- precompiled binaries don't work on other OS's or architectures
- when switching versions of binaryen, one has to know special things to ensure one has the corresponding versions of the precompiled binaries
- auto-downloading precompiled binaries is a non-trivial non-hermeticism

Two possible ways to solve this are:
- Instead of downloading precompiled binaries and using them to generate tests for binaryen as part of binaryen's test script, generate the tests offline and check the results into binaryen's repo, so that users can run them without using the precompiled binaries.
- Put tests for integration between binaryen and other components into a separate repo, which can build all the components from source.

**Comment by rwtolbert** [comment] 2016-03-21 13:04
:thumbsup: 

I spent some time this weekend making the build happy using VS2015. Just a few small changed here and there and I can do everything _except_ run the tests that assume they can download and run a pre-built executable.

But I know this is a young project, so I'm not sure if there is too much churn to keep Windows/VS2015 as a first-class build platform or if there are too many daily changes to keep test output checked in as opposed to re-generating it locally.

I'd love to help with both, just don't want to get in the way.

and if there is a better place to discuss, let me know.

**Comment by kripken** [comment] 2016-03-21 17:33
cc @jfbastien 

We should already notice if you can't run the executable and just warn on that. Is that not enough for you, @sunfishcode? I.e., are you bothered by the warning? Or did the warning not work properly?

Another option is to download and build LLVM and clang locally. This might help the VS case that you mention, @rwtolbert. If someone wants to do that work to add it as an option, sounds good to me.

However, keeping the option for downloading the waterfall is crucial: it's the only way we can use Travis CI. And, downloading the linux64 executables works in the common case - my machine, most other devs I know, and the google bots - so I think that's useful.

**Comment by rwtolbert** [comment] 2016-03-21 20:19
I think being able to also use a locally built LLVM should work. At least now I see the reason for the current behavior.

Turns out, I only thought that was my problem on Windows. Actually, I'm crashing in a real test (binary-shell) that should work with out that piece, so I need to dig deeper into the cause of that problem first.

**Comment by jfbastien** [comment] 2016-03-22 17:03
I agree that it should be possible to run the tests without downloading any binaries. Isn't that already the case though? I thought the waterfall and emscripten binaries could be turned off / redirected?

**Closed** 2024-12-13 21:01 UTC
