### ISSUE TITLE
Fatal Error in wasm-as.exe when parsing a parameter of type "none"

### ISSUE THREAD

**Issue by alexandrelessard** [WebAssembly/binaryen#869] opened 2017-01-04 15:24 UTC
hi, 

I just upgraded to 1.37.1 (up from 1.35.20)
(and enabled -s WASM=1 -s \"BINARYEN_METHOD=\'interpret-binary\'\")

And I am now getting this error:
(i did compile the Debug version of the wasm-as.exe application so I could get more information)

The Error happens in:
\binaryen\binaryen-version_21\src\wasm\wasm-s-parser.cpp

the function:
WasmType SExpressionWasmBuilder::stringToWasmType(const char* str, bool allowError, bool prefix) {
  if (str[0] == 'i') {
    if (str[1] == '3' && str[2] == '2' && (prefix || str[3] == 0)) return i32;
    if (str[1] == '6' && str[2] == '4' && (prefix || str[3] == 0)) return i64;
  }
  if (str[0] == 'f') {
    if (str[1] == '3' && str[2] == '2' && (prefix || str[3] == 0)) return f32;
    if (str[1] == '6' && str[2] == '4' && (prefix || str[3] == 0)) return f64;
  }
  if (allowError) return none;
  abort();
}
Is Aborting.
The cause seems to be str == ("none")

With some debugging I figured the "none" came from my *.wast file:

At some point the wast file contains:
  (type $FUNCSIG$vid (func (param i32 f64)))
  (type $FUNCSIG$vidddd (func (param i32 f64 f64 f64 f64)))
  (type $FUNCSIG$iiid (func (param i32 i32 f64) (result i32)))
  (type $FUNCSIG$vdi (func (param f64 i32)))
  (type $FUNCSIG$ivi (func (param none i32) (result i32)))
  (type $FUNCSIG$ivii (func (param none i32 i32) (result i32)))
  (type $FUNCSIG$iviii (func (param none i32 i32 i32) (result i32)))

And the application bails out on the first occurrence of the "none" parameter type.

From this point I ignore if the problem is the the "none" parameter type or if it is the parser that should support "none".

Any information would be greatly appreciated

-Alex

**Comment by kripken** [comment] 2017-01-04 19:04
That definitely looks like a bug, somehow we miscompiled the param type - `none` is not valid there. Can you provide the code to reproduce the problem? Or if not perhaps reduce it to a testcase you can provide?

**Comment by alexandrelessard** [comment] 2017-01-06 18:30
Thanks for the quick response.
I am not in a position to provide easily the full setup to repro this situation.
I will find a simplified setup hopefully next week to help that, 

Thanks

**Comment by alexandrelessard** [comment] 2017-01-10 16:37
I can provide a way for you to repro the "none" generation.
[IntegrationDemo.asm.js.zip](https://github.com/WebAssembly/binaryen/files/696738/IntegrationDemo.asm.js.zip)

(using 1.37.1 tool chain)

Have an version of asm2wasm.exe with debug symbols.
Add a breakpoint in:
\binaryen\binaryen-version_21\src\wasm.h

inside the none case:
inline const char* printWasmType(WasmType type) {
  switch (type) {
    case WasmType::none: 
        return "none";

and run the following command:
asm2wasm integrationDemo.asm.js --wasm-only
on this file:
[IntegrationDemo.asm.js.zip](https://github.com/WebAssembly/binaryen/files/696738/IntegrationDemo.asm.js.zip)

These "none" will cause crashes int he wasm-as.exe later in the pipeline.

Thanks

**Comment by kripken** [comment] 2017-01-10 19:03
Thanks. I get

````
HEAP32
asm2wasm: /home/alon/Dev/binaryen/src/asm2wasm.h:1347: wasm::Asm2WasmBuilder::processFunction(cashew::Ref)::<lambda(cashew::Ref)>: Assertion `mappedGlobals.find(name) != mappedGlobals.end() ? true : (std::cerr << name.str << '\n', false)' failed.
Aborted (core dumped)
````

and looking in the code, the source of that `HEAP32` is in atomics/pthreads code. We should give an error on using that with wasm, because wasm doesn't have support for it yet.

When I strip out the atomics code manually, then I run asm2wasm, the output is free from `none`, so it looks like that is the cause of the problem you saw.

Does your codebase require atomics/pthreads?

**Comment by alexandrelessard** [comment] 2017-01-10 19:13
Yes i am using both at the moment.

**Comment by kripken** [comment] 2017-01-10 19:16
I see, ok. Then wasm isn't an option for you yet, pthreads and atomics are on the roadmap but there is no spec or impl yet.

I opened https://github.com/kripken/emscripten/pull/4849 to show a clear error message for this, sorry for the confusion.

Closing this issue as the cause is not something we can fix in binaryen.

**Closed by kripken** 2017-01-10 19:16 UTC
