### ISSUE TITLE
Is it possible to get an explanation of what these codes do in the following path: binaryen/test/passes/

### ISSUE THREAD

**Issue by shrin18** [WebAssembly/binaryen#2337] opened 2019-09-11 06:59 UTC
Hello,

We are experimenting with WASM and have selected 10 programs from this passes to run our super-optimiser algorithm on. Is it possible to provide an explanation for what each of the program does in this case ?

Thanks in advance.

**Comment by tlively** [comment] 2019-09-11 16:34
The files in `binaryen/test/passes/` are mostly just input for unit and regression tests, so they don't do much of anything. They probably aren't interesting for anything beyond that purpose either. What kind of test cases are you looking for?

**Comment by tlively** [comment] 2019-11-06 01:58
I'll close this for now because there doesn't seem to be anything actionable. Please feel free to re-open if you disagree.

**Closed by tlively** 2019-11-06 01:58 UTC
