### ISSUE TITLE
UNREACHABLE executed at Precompute.cpp:838 on Windows

### ISSUE THREAD

**Issue by JSMonk** [WebAssembly/binaryen#6710] opened 2024-07-03 08:32 UTC
Version: 117
Platform: Windows 11 (x64)

Using `-O2` and higher on Windows produces `UNREACHABLE executed at Precompute.cpp:838` error.
I've attached the binary that helps to reproduce the behavior.

[stardew-valley-designer-app-web-wasm-js.wasm.zip](https://github.com/user-attachments/files/16080804/stardew-valley-designer-app-web-wasm-js.wasm.zip)

To reproduce the failure, take the binary and run the following command:
```
wasm-opt.exe --all-features -O2 .\stardew-valley-designer-app-web-wasm-js.wasm -o output.wasm
```

To generate the binary by yourself:
1. Clone repo: https://github.com/AzimMuradov/stardew-valley-designer
2. Create `local.properties` file with the following content: `kotlin.daemon.jvmargs=-Xmx2048m`
3. Run `./gradlew.bat :app-web:compileProductionExecutableKotlinWasmJs`
4. The binary is located in the following directory: `app-web\build\compileSync\wasmJs\main\productionExecutable\kotlin`

**Comment by kripken** [comment] 2024-07-03 14:56
Looks like a duplicate of #6639 which has been fixed meanwhile on `main` (but is not yet in a release).

**Comment by JSMonk** [comment] 2024-07-05 15:01
@kripken when the next version release is planned? We would really happy to update to the version with this fix as soon as possible

**Comment by kripken** [comment] 2024-07-08 20:43
@JSMonk I tagged version 118 now (still building atm).

**Closed** 2024-12-13 20:30 UTC
