### ISSUE TITLE
TypeMerging error on call param

### ISSUE THREAD

**Issue by kripken** [WebAssembly/binaryen#5877] opened 2023-08-14 20:13 UTC
```wat
(module
 (rec
  (type $A (func (param (ref null $Y )) (result f64)))
  (type $B (sub $A (func (param (ref null $B)) (result f64))))
  (type $C (sub $A (func (param (ref null $A)) (result f64))))

  (type $X (sub $B (func (param (ref null $A)) (result f64))))
  (type $Y (sub final $X (func (param funcref ) (result f64))))
 )

 (func $0 (type $X) (param $0 (ref null $A)) (result f64)
  (unreachable)
 )
 (func $1 (param $1 (ref null $B))
  (unreachable)
 )
 (func $2 (param $0 (ref $Y ))
  (call $1
   (ref.func $0)
  )
 )
 (func $4 (result (ref null $C))
  (unreachable)
 )
)
```
```bash
$ bin/wasm-opt a.wat -all --closed-world --type-merging
[wasm-validator error in function 2] call param types must match, on 
(call $1
 (ref.func $0)
)
(on argument 0)
Fatal: error after opts
```
cc @tlively

**Comment by tlively** [comment] 2023-08-22 21:00
Took a look and it looks like the way we're creating partitions for supertype merging is not as correct as I thought it was. Here's another broken example:

```wasm
(module
 (type $I (sub    (struct (field anyref))))
 (type $J (sub $I (struct (field eqref))))
 (type $K (sub $J (struct (field i31ref))))
 (rec
  (type $A  (sub    (struct (ref null $A) (ref null $I))))
  (type $B  (sub $A (struct (ref null $B) (ref null $J))))
  (type $C  (sub $A (struct (ref null $A) (ref null $K))))
  (type $D1 (sub $B (struct (ref null $B) (ref null $K))))
  (type $D2 (sub $C (struct (ref null $B) (ref null $K))))
 )

 (global $g1 (ref $B) (struct.new_default $D1))
 (global $g2 (ref $C) (struct.new_default $D2))
)
```

The main type hierarchy looks like this:

```
A
| \
B  C
|  |
D1 D2
```

All these types have the same top-level structure, so they all get put into A's initial DFA partition. The I, J, and K auxiliary types cause A, B, and C to all be differentiable, so after partition refinement, D1 and D2 are left in a partition together, so they are merged. No matter whether we merge D1 into D2 or vice versa, either `g1` or `g2` will fail validation.

The problem is that during the supertype merging phase, we are allowing unrelated types D1 and D2 to be merged into each other after partition refinement discovers that they cannot be merged with their common ancestors.

The best fix I can think of is to post-process the refined partitions and manually split each partition into a new partition for each of its root types. After that manual splitting, we'll have to re-run partition refinement, so this will have to be done in a loop.

**Closed** 2023-08-24 04:55 UTC
