### ISSUE TITLE
Syntax error while installing emsdk

### ISSUE THREAD

**Issue by lavi061997** [WebAssembly/binaryen#1096] opened 2017-07-16 15:29 UTC
PS C:\Users\Lakshya-PC\Desktop\Project\emsdk> ./emsdk install sdk-incoming-64bit binaryen-master-64bit
  File "C:\Users\Lakshya-PC\Desktop\Project\emsdk\\emsdk", line 109
    except Exception, e:

This syntax error while installing emsdk

**Comment by dcodeIO** [comment] 2017-07-16 15:34
The [emsdk repository](https://github.com/juj/emsdk) might be a better place for emsdk related issues.

**Comment by juj** [comment] 2017-07-17 17:39
Perhaps you have python 3 installed through which `emsdk` is running? Emsdk should be run on python 2, though just recently I did update it to be python 3 compatible again: https://github.com/juj/emsdk/commit/fd087c100da863752d5a892b7b7cecfdb0523731.

Let me close this, feel free to reopen in https://github.com/juj/emsdk if that was not the cause and the issue still persist (try `emsdk update` or `git clone https://github.com/juj/emsdk.git` to get the above update)

**Closed by juj** 2017-07-17 17:39 UTC
