### ISSUE TITLE
Bad file data after wasmReallocBuffer call

### ISSUE THREAD

**Issue by metalpavel** [WebAssembly/binaryen#1118] opened 2017-07-31 12:19 UTC
Here is example:
```
#include <iostream>
#include <cstdio>
#include <string>
#include <vector>

bool loadMyFile() {
    FILE * f = fopen("text.txt" , "rb");
    if (!f) {
        std::cout << "unable to open file" << std::endl;
        return false;
    }
    fseek(f, 0, SEEK_END);
    int size = ftell(f);
    rewind(f);

    std::cout << "file size: " << size << std::endl;

    std::string buffer;
    buffer.resize(size);

    size_t readed = fread(&buffer[0], 1, size, f);
    fclose(f);

    if(readed != size) {
        std::cout << "wrong read: " << readed << "/" << size << std::endl;
    }

    return buffer == "Lorem ipsum dolor sit amet, consectetur adipiscing elit.";
}

int main(int argc, char ** argv) {
    bool result = loadMyFile();

    std::cout << "test before alloc: " << result << std::endl;

    const size_t testBufferSize = 1024 * 1024 * 32;

    std::vector<char> testData(testBufferSize);

    if(testData.size() != testBufferSize) {
        std::cout << "wrong buffer size: " << testData.size() << std::endl;
    }

    result = loadMyFile();

    std::cout << "test after alloc: " << result << std::endl;

    return 0;
}
```
Compile command: `emcc hello.cpp -O3 -s WASM=1 --emit-symbol-map --bind -s TOTAL_MEMORY=16777216 -s ALLOW_MEMORY_GROWTH=1 --memory-init-file 1 -o hello.html --preload-file text.txt`

text.txt data:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
```

Chrome (Version 59.0.3071.115 (Official Build) (64-bit)) output:
```
file size: 56
test before alloc: 1
file size: 56
test after alloc: 0
```
Firefox (54.0.1 (64-bit)) output:
```
file size: 56
test before alloc: 1
file size: 56
TypeError: attempting to access detached ArrayBuffer
```

Any work around for this case? Is this browser error? Allocation of huge memory block on start will solve this problem, but this is bad.

**Comment by metalpavel** [comment] 2017-07-31 13:53
possible duplicate https://github.com/kripken/emscripten/issues/5179

**Comment by kripken** [comment] 2017-07-31 18:26
Yes, looks like a duplicate of that, closing this one.

I think this is more of an issue now because wasm makes memory growth more useful. Before very few people used memory growth in asm.js, so bugs there went unnoticed.

**Closed by kripken** 2017-07-31 18:26 UTC
