### ISSUE TITLE
wasm-opt --dfo crashes

### ISSUE THREAD

**Issue by hpohl** [WebAssembly/binaryen#2008] opened 2019-04-13 23:10 UTC
Using it on [this file](https://s3.eu-central-1.amazonaws.com/trail-public/tmp/orig.wasm):
```
$ wasm-opt orig.wasm -o opt.wasm --dfo
Segmentation fault (core dumped)
```

**Comment by tlively** [comment] 2019-04-14 06:40
Reduced reproducer: https://gist.github.com/tlively/4bc2a727cb956bc474b85d97edd9a9b6

**Comment by kripken** [comment] 2019-04-14 22:52
Thanks! Looks like the same issue as #2007, that we don't give a proper error on IR not being flat when it is expected to be. Fix in #2009

**Comment by kripken** [comment] 2019-04-16 17:02
Fixed by that PR.

**Closed by kripken** 2019-04-16 17:02 UTC
