### ISSUE TITLE
Output WASM file sizes

### ISSUE THREAD

**Issue by briancullinan** [WebAssembly/binaryen#4730] opened 2022-06-15 02:30 UTC
https://github.com/WebAssembly/wasi-sdk/issues/163#issuecomment-1155904109

I was using version 107 or something until I irresponsibly ran `brew upgrade` thinking nothing of it. Now binaryen does not shrink my output WASMs. It does nothing for me. No error messages, no confirmations, no verbose `-v` option reports (Unknown option `-v`, which is just bad design for linux).

Version 91 is the last known version to work for me, and it is still compiling correctly in Github Actions on Ubuntu. I just download version 91 for MacOS and it works as expect.

Binaryen has working versions available on Ubuntu, but they are not updated. So if anybody comes along looking for an update, their build will immediately be broken because the version available in Ubuntu is so vastly different from the latest version.
^^^ That issue in itself, has nothing to do with me. Binaryen needs to focus on updating Ubuntu's package manager.

Is there some option that I need to add? I tried looking at the Release log but there are not changelog messages that might help me determine which options changed. Would be nice if it defaulted to the same behavior. Something just changed, so I am opening an issue. This must not be an issue with my project because I just downloaded version 91 and it works as expected.

Is there some way I should add CI to this repo to test other people's projects?
This is really baffling to me, and doesn't happen to me often. Last time was in 2019 when Mac changed something in the display driver that required this line: https://github.com/ioquake/ioq3/issues/422#issuecomment-541225342
Look how nuanced that is. How incredibly difficult to figure out?

Next step: Test every version on MacOS for breaking changes (I thought this was done already, but I guess I'll do it).

**Comment by kripken** [comment] 2022-06-15 04:11
There are binaries for the major platforms available here on github. If there are issues with the builds brew or some other package manager provides, perhaps try those?

https://github.com/WebAssembly/binaryen/releases

I can't think of a flag that changed that would prevent optimization. That sounds very strange. If you can't easily figure this out with those builds, please provide the full `wasm-opt` command you are running and the binary you are running it on, so we can help.

**Comment by briancullinan** [comment] 2022-06-16 22:30
Okay. I tested more versions, and version 98 works but version 99 does not. 

version 98 I get a warning
```
warning: unknown name subsection with id 9 at 22674751
```

before that I go the warning:
```
unknown name subsection at 22674731
unknown name subsection at 22674751
```

So something to do with solving those warnings, makes wasms come out to be 22MB instead of 1MB and filled with zeros.

**Comment by kripken** [comment] 2022-06-16 22:39
The only possible theory I could have is if the name section is invalid, binaryen might drop it rather than rewrite it. But you don't have `-g` so there is no name section relevant anyhow...

In any case, if you can't figure this out, please provide a full testcase we can reproduce this with: a wasm file + a `wasm-opt` command that optimizes to 1MB in v98 but turns into 21MB in v99. Such a huge regression should be very fast for us to figure out.

**Comment by kripken** [comment] 2022-06-16 22:50
Oh, actually I had another idea: #3306 It fits as it landed in v99.

If that's it, it's a bugfix for behavior that was wrong before, so we had no choice but to fix it. But it can regress size. To confirm, try adding `--zero-filled-memory`. Looks like that's not in the changelog, which is bad - I'll add that now.

Btw, in general, it's safer to let emscripten run wasm-opt for you, as it will supply the right flags automatically, which avoids stuff like this.

**Comment by briancullinan** [comment] 2022-06-16 23:12
That's it!!!  OMG, did the default behavior change? I need a WARNING: message if file size doesn't change.


> Oh, actually I had another idea: #3306 It fits as it landed in v99.
> 
> If that's it, it's a bugfix for behavior that was wrong before, so we had no choice but to fix it. But it can regress size. To confirm, try adding `--zero-filled-memory`. Looks like that's not in the changelog, which is bad - I'll add that now.
> 
> Btw, in general, it's safer to let emscripten run wasm-opt for you, as it will supply the right flags automatically, which avoids stuff like this.


Maybe that is part of the problem. I am compiling Q3e directly to wasm with WASI-sdk, no more Emscripten mess! My build is easily 2X faster than QuakeJS.

**Comment by kripken** [comment] 2022-06-16 23:56
Good, glad we figured this out. Btw, if you're building with wasi-sdk then another flag you might want is `--low-memory-unused`. That's the other main flag emscripten passes by default to `wasm-opt`, that you need to pass manually otherwise. It does require you to ensure low memory is actually unused, though, which I'm not sure how to do in wasi-sdk. But that flag is usually just a few % of improvement to size and speed.

**Closed** 2022-06-17 14:35 UTC

**Comment by tlively** [comment] 2022-06-17 17:05
Smaller Wasm modules are generally better. Especially for the data section, there's no reason to prefer a larger one.

An integration test making sure that wasi-sdk + binaryen gets all the expected optimizations would be useful, but this would not be the right repo for it IMO. If there were more of an integration between wasi-sdk and Binaryen, the wasi-sdk repo would make more sense. But AFAIK there's not really an integration to test.

The zeroes you're seeing might be .bss, yes, but I thought that the linker skipped emitting .bss sections in most configurations. I don't remember exactly.

**Comment by kripken** [comment] 2022-06-17 17:06
> There should be a failed test for a program generated with lots of static memory and then wasm-opt not affecting the output.

I agree with @tlively that there isn't something to do in this repo. We already have tests for doing the right thing when that flag is passed (unit tests on the `PackMemory` pass). But we can't expect that to work without the flag, sadly (as mentioned before, it's just incorrect to assume memory is zeroed).

But I agree we can improve things here. Another option might be adding some kind of docs on the `wasi-sdk` side, explaining how crucial this binaryen flag is? Hopefully other `wasi-sdk` users would see that and avoid the problem you ran into. I'm not sure exactly where such docs would go, however.

**Comment by briancullinan** [comment] 2022-06-17 21:39
I'm always assuming I have some oddball setup, making things more difficult for myself. Thanks to Google's user-mandated BUBBLE. Here's my top 5 search results for `"zero-filled-memory" wasm-opt`

https://github.com/emscripten-core/emscripten/issues/15340
https://github.com/WebAssembly/binaryen
https://rustrepo.com/repo/christopher-kleine-wasm-4-tutorial-games-rust-games
https://yonghwi-kwon.github.io/data/wasm_ase21.pdf
https://forum.unity.com/threads/cant-make-unity-2021-3-0f-build-webgl.1269599/

I wouldn't assume that zero-filled-memory is common enough that anyone other than us should know about it. But doing a search like this, `wasi-sdk wasm-opt`, is a sign this is bleeding edge technology?

https://github.com/WebAssembly/wasi-sdk
https://github.com/WebAssembly/wasi-sdk/releases
https://bytecodealliance.github.io/cargo-wasi/wasm-opt.html
https://www.dynamsoft.com/codepool/wasi-sdk-zxing-barcode-wasm.html
https://memgraph.com/blog/wasm-a-tour-of-the-webassembly-ecosystem

> I'm not sure exactly where such docs would go, however.

Hence, we don't know where the docs are, maybe because there aren't any? This is so strange. I feel like Google was really good 10 years ago and now I feel more lost.

**Comment by tlively** [comment] 2022-06-17 22:46
I would expect users to discover `--zero-filled-memory` by reading our `--help` output (and now by reading the release notes as well). Arguably there should be a wiki page or something with all the tool options, but it would mostly duplicate all the information already in `--help`.
