### ISSUE TITLE
Implicit function types and rec types

### ISSUE THREAD

**Issue by chambart** [WebAssembly/binaryen#5355] opened 2022-12-15 17:23 UTC
I would have expected this to be valid
```wast
(module

  (rec
    (type $Func_1
      (func (param (ref eq)) (param (ref $Env)) (result (ref eq))))
    (type $Env (struct (field (mut i8)) (field (mut (ref $Func_1))))))

  (elem declare func $implicit)
  (elem declare func $explicit)

  (func $implicit (param (ref eq)) (param (ref $Env)) (result (ref eq))
    (local.get 0))

  (func $explicit (type $Func_1)
    (local.get 0))

  (func (export "implicit") (result (ref $Func_1))
    (ref.func $implicit))

  (func (export "explicit") (result (ref $Func_1))
    (ref.func $explicit))

)
```

But the `implicit` function does not have the type `Func_1` as demonstrated by the function `(export "implicit")` that does not typecheck.

Not that this example (without recursive types) does typecheck

```wast
(module

  (type $Env (struct (field (mut i8))))
  (type $Func_1
    (func (param (ref eq)) (param (ref $Env)) (result (ref eq))))

  (elem declare func $implicit)
  (elem declare func $explicit)

  (func $implicit (param (ref eq)) (param (ref $Env)) (result (ref eq))
    (local.get 0))

  (func $explicit (type $Func_1)
    (local.get 0))

  (func (export "implicit") (result (ref $Func_1))
    (ref.func $implicit))

  (func (export "explicit") (result (ref $Func_1))
    (ref.func $explicit))

)
```

Also both version typecheck according to the current version of the reference implementation (of the gc proposal)

**Comment by tlively** [comment] 2022-12-15 18:28
I believe this is working as intended, although it's interesting that the reference implementation disagrees.

The implicit type is `(type (func (param (ref eq) (ref $Env)) (result (ref eq))))`, which is a type in a recursion group of size one. That implicit type has a different identity than `$Func_1` in the example above since `$Func_1` is in a recursion group of size 2.

I've opened https://github.com/WebAssembly/gc/issues/344 to get clarity on the intended behavior here.

**Comment by tlively** [comment] 2022-12-15 23:06
Ok, confirmed upstream that this is working as intended and Andreas has landed a fix to the reference interpreter. I'll go ahead and close this, but feel free to reopen if you have further questions.

**Closed by tlively** 2022-12-15 23:06 UTC

**Comment by chambart** [comment] 2022-12-15 23:57
That was quite fast. Thanks for the clarification.
