### ISSUE TITLE
wasm-opt transforms bulk memory operations into nops with --precompute 

### ISSUE THREAD

**Issue by Aransentin** [WebAssembly/binaryen#1984] opened 2019-04-06 23:39 UTC
The following program fills 32 bytes of the exported memory using `memory.fill`:

```
(module
 (type $0 (func (param i32)))
 (memory $0 1 1)
 (export "memory" (memory $0))
 (export "testfunc" (func $0))
 (func $0 (; 0 ;) (type $0) (param $0 i32)
  (memory.fill
   (i32.const 1024)
   (local.get $0)
   (i32.const 32)
  )
 )
)
```

Running wasm-opt on it with no optimizations (`wasm-opt -O0 --enable-bulk-memory test.wasm -o test.opt.wasm`) unsurprisingly changes nothing, but if you add `--precompute` it replaces the `memory.fill` with `nop`:

```
(module
 (type $0 (func (param i32)))
 (memory $0 1 1)
 (export "memory" (memory $0))
 (export "testfunc" (func $0))
 (func $0 (; 0 ;) (type $0) (param $0 i32)
  (nop)
 )
)
```

**Comment by tlively** [comment] 2019-04-07 00:34
Thanks for the report! This is probably because the interpreter for bulk memory ops has not been implemented yet. This should be fixed early next week.

**Comment by kripken** [comment] 2019-04-07 01:23
Hmm, yeah, we missed a bunch of stuff here. We should make the `EffectAnalyzer` inherit from `OverridingVisitor` so that we get compile errors if we forget a class.

**Comment by kripken** [comment] 2019-04-17 02:38
I believe this has been done.

**Comment by tlively** [comment] 2019-04-17 06:07
Not quite. We fixed effects.h, but the root cause of this bug was indeed the lack of interpretation. I have a WIP that is nearly done, but it's taken a back burner to the latest waterfall fires.

**Closed** 2019-04-18 03:08 UTC
